Pain: "Restructuring of the project"
skfl/andersen-task pull request #48
Opened 2023-04-11 19:00 UTC by ulad-sachkovski

Pain

2023-04-12 15:34 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/book/services/BookService.java
> +        Optional<Book> optionalBook = getBookById(id);
this method does not save changes

2023-04-12 15:42 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/book/services/BookService.java
> +        for (Long id : ids) {
stream api?

2023-04-12 15:46 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +import java.util.*;
it is better to avoid wild card import

2023-04-12 15:58 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +                appContextConfig.getRequestService().deleteRequest(book);
looks like unreachable statement
because:
on line 31 you actually comparing bookStatus(because you taking status of the book which was updated by bookStatus, so you can just compare bookStatus) and BookStatus.OUT_OF_STOCK 
and then
you want bookStatus to be BookStatus.AVAILABLE
I`m not sure, because i quickly looked through, could you please check it?

2023-04-12 16:20 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        if (optionalBook.isPresent()) {
we can use ifPresent
to discuss

2023-04-12 16:51 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        if (booksToOrder.size() == ids.size()) {
Wierd check
because nothing happens if customer filled in non-existent id

2023-04-12 16:56 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +            Order order = appContextConfig.getEntityFactory().buildOrder(booksToOrder);
looks like you don`t know if booksToOrder contains only Available books

2023-04-12 17:12 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +            booksToRequest.forEach(x -> appContextConfig.getEntityFactory().buildRequest(x));
looks like you build requests but don`t save them

2023-04-12 17:12 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        }
to discuss

2023-04-12 17:25 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +            if (orderStatus.equals(OrderStatus.COMPLETED)) {
Also should be an order status check

2023-04-12 17:26 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +                if (allBooksAreAvailable){
i would do it like this
if (appContextConfig.getBookService().allBooksAreAvailable(order.getBooksInOrder()))

2023-04-12 17:28 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        return appContextConfig.getOrderService().getSortedOrders(orderSort);
method chaining
from the new line

2023-04-12 17:29 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        return appContextConfig.getOrderService().getSortedOrders(orderSort);
i mean not only in this method

2023-04-12 17:53 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +    public List<Book> getAllBooksFromOrder(Long id) {
why do you need this method in Commands?

2023-04-12 17:58 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/UserCommunication.java
> +public class UserCommunication {
What the purpose of this class?

2023-04-12 18:06 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +                appContextConfig.getOrderService().changeStatusOfOrder(id, orderStatus);
to discuss

2023-04-12 18:07 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/order/service/OrderService.java
> +        if (optionalOrder.isPresent()) {
ifPresent?

2023-04-12 18:07 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        return appContextConfig.getOrderService().getSortedOrders(orderSort);
to discuss

2023-04-12 18:10 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/request/services/RequestService.java
> +    public Optional<Request> getRequestById(Long id) {
i think that`s bad to return optional in service

2023-04-12 18:14 UTC, DenisBratuh requested changes
<3

2023-04-13 05:17 UTC, DenisBratuh requested changes

2023-04-13 05:17 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/command/GetBooks.java
> +import com.andersentask.bookshop.console.ConsoleAppController;
unused imports

2023-04-13 05:17 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/command/GetBooks.java
> +public class GetBooks implements Command {
why do we need new class for one method?

2023-04-13 05:17 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/ConsoleAppController.java
> +        while (true) {
how we will use this method with while(true)?

2023-04-13 05:17 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/UserCommunication.java
> +        Long id = Long.valueOf(parameter);
is it necessary to declare this variables explicitly?

2023-04-13 05:17 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/UserCommunication.java
> +        System.out.println(DefaultMessages.HELP_MESSAGE.getValue());
Log instead of sout

2023-04-13 05:17 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/console/UserCommunication.java
> +        List<String> userInput = Arrays.stream(input.split(" ")).toList();
method chaining 
from new line

2023-04-13 08:52 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/book/repositories/BookRepository.java
> +        for (Book book : books) {
I don't know, how to refactor findById with stream in repositories.. Any idea?

2023-04-13 08:55 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/book/services/BookService.java
> +        for (Long id : ids) {
method iterates by ids. I think, this can not be done with streams

2023-04-13 09:03 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +                appContextConfig.getRequestService().deleteRequest(book);
Denis, ti krasav4ik <3
I made changes, see in the next commint

2023-04-13 09:05 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        if (optionalBook.isPresent()) {
I have no idea, how to do this :(
I thought about it and came to this version with ifPresent() check

2023-04-13 09:15 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        if (booksToOrder.size() == ids.size()) {
<3
now method returns Optional<Order>
If the order is not created, Optional is empty

in User Communication class we will sout, that input is invalid, if optional is empty

2023-04-13 09:16 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +            Order order = appContextConfig.getEntityFactory().buildOrder(booksToOrder);
books in order can be both available and out_of_stock
when all books become available, the order can be completed
(new logic)

2023-04-13 09:22 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +            booksToRequest.forEach(x -> appContextConfig.getEntityFactory().buildRequest(x));
Agree, I changed the code

2023-04-13 09:29 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +                appContextConfig.getOrderService().changeStatusOfOrder(id, orderStatus);
What checks do you mean?

2023-04-13 09:32 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +    public List<Book> getAllBooksFromOrder(Long id) {
We have the task to show all information about the order: books, users
as we have no users, we will just show books

2023-04-13 09:32 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        return appContextConfig.getOrderService().getSortedOrders(orderSort);
oki

2023-04-13 09:33 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +                if (allBooksAreAvailable){
nice

2023-04-13 09:36 UTC, skfl commented on src/main/java/com/andersentask/bookshop/console/EntityFactory.java
> +public class EntityFactory {
i do not really think that factory is good name for such class

2023-04-13 09:37 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +            if (orderStatus.equals(OrderStatus.COMPLETED)) {
In Commands we add additional logic to this method
Order turns to completed only when all books are available (this info keeps bookService)
That's we need this method in commands with additional check to bool availability

I changed the name of the method to "changeStatusOfOrderIncludingBooksCheck"

2023-04-13 09:37 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/Commands.java
> +        }
oki, let's discuss

2023-04-13 09:40 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/ConsoleAppController.java
> +    private <T> void printListData(List<T> list) {
It was Ed's method and did just function of toString() of list
let's remove for this moment and just use basic @toString from Lombok

2023-04-13 09:42 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/order/service/OrderService.java
> +        if (optionalOrder.isPresent()) {
I think, it's impossible

2023-04-13 09:52 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/request/repository/RequestRepository.java
>          for (Request request : requests) {
I think, it's impossible..

2023-04-13 09:53 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/command/GetBooks.java
> +import com.andersentask.bookshop.console.ConsoleAppController;
this package will be deleted
Anton did it j4f

2023-04-13 09:53 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/command/GetBooks.java
> +public class GetBooks implements Command {
this package will be deleted
Anton did it j4f

2023-04-13 09:57 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/console/ConsoleAppController.java
> +        while (true) {
I don't know, why in while it goes to init() method
Now when user types "exit", System.exit(0) is called

2023-04-14 09:54 UTC, merged