Fix: "Services and repositories"
skfl/andersen-task pull request #64
Opened 2023-04-16 10:13 UTC by ulad-sachkovski

--sort and get methods moved to repositories
--enhancement of some methods in repositories and services

2023-04-16 14:15 UTC, DenisBratuh requested changes

2023-04-16 14:15 UTC, DenisBratuh commented on src/main/java/com/andersentask/bookshop/request/services/RequestService.java
> +    public Long getNumberOfRequestsOnBook(Long bookId) {
looks like this method should be in repository too

2023-04-17 05:01 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/book/services/BookService.java
>          for (Long id : ids) {
мне кажется, что через луп код выглядел проще, ну да ладно...

2023-04-17 05:03 UTC, ulad-sachkovski commented on src/main/java/com/andersentask/bookshop/book/services/BookService.java
они не должны быть в репе, т.к. они не тянут данные с БД
они принимают лист книг как параметр:
allBooksAreAvailable => для того, чтобы выполнить заказ
getBooksOutOfStock => для создания реквеста, если в заказ пришли аут_оф_сток книги

2023-04-17 09:16 UTC, skfl approved these changes

2023-04-17 09:22 UTC, merged